version: '3'
services:
  postgres:
    image: postgres
    volumes:
      -  postgresql-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=rw_dev
      - POSTGRES_USER=rw_dev
      - POSTGRES_DB=rw_development
    ports:
      - "5432:5432"
    # networks:
    #   - postgres-net
  pgadmin:
    image: fenglc/pgadmin4
    links:
      - postgres:postgres    
    environment:
       - DEFAULT_USER=pgadmin@mail.com
       - DEFAULT_PASSWORD=mypassword
    volumes:
       - postgresql-volume:/root/.pgadmin
    ports:
      - "5050:5050"
    # networks:
    #   - postgres-net
    restart: unless-stopped
# networks:
#   postgres-net:
#     driver: bridge
volumes:
    postgresql-volume:
      external: true
